# Generated by Django 3.0.8 on 2020-08-17 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('public_email', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('year_of_born', models.CharField(blank=True, choices=[('1330', '1330'), ('1331', '1331'), ('1332', '1332'), ('1333', '1333'), ('1334', '1334'), ('1335', '1335'), ('1336', '1336'), ('1337', '1337'), ('1338', '1338'), ('1339', '1339'), ('1340', '1340'), ('1341', '1341'), ('1342', '1342'), ('1343', '1343'), ('1344', '1344'), ('1345', '1345'), ('1346', '1346'), ('1347', '1347'), ('1348', '1348'), ('1349', '1349'), ('1350', '1350'), ('1351', '1351'), ('1352', '1352'), ('1353', '1353'), ('1354', '1354'), ('1355', '1355'), ('1356', '1356'), ('1357', '1357'), ('1358', '1358'), ('1359', '1359'), ('1360', '1360'), ('1361', '1361'), ('1362', '1362'), ('1363', '1363'), ('1364', '1364'), ('1365', '1365'), ('1366', '1366'), ('1367', '1367'), ('1368', '1368'), ('1369', '1369'), ('1370', '1370'), ('1371', '1371'), ('1372', '1372'), ('1373', '1373'), ('1374', '1374'), ('1375', '1375'), ('1376', '1376'), ('1377', '1377'), ('1378', '1378'), ('1379', '1379'), ('1380', '1380'), ('1381', '1381'), ('1382', '1382'), ('1383', '1383'), ('1384', '1384'), ('1385', '1385'), ('1386', '1386'), ('1387', '1387'), ('1388', '1388'), ('1389', '1389'), ('1390', '1390'), ('1391', '1391'), ('1392', '1392'), ('1393', '1393'), ('1394', '1394')], max_length=4, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('work', models.CharField(blank=True, max_length=50, null=True)),
                ('rezome', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('body', models.TextField()),
                ('likes', models.CharField(default='0', max_length=3)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Programming',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('link_on_github', models.CharField(blank=True, max_length=100, null=True)),
                ('link_on_gitlab', models.CharField(blank=True, max_length=100, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Person')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('replay', models.CharField(blank=True, max_length=1000, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Person')),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Project')),
            ],
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('replay', models.CharField(blank=True, max_length=1000, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Person')),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Post')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='likes',
            field=models.ManyToManyField(blank=True, to='main.Post'),
        ),
        migrations.AddField(
            model_name='person',
            name='programming',
            field=models.ManyToManyField(blank=True, to='main.Programming'),
        ),
    ]
