# Generated by Django 3.0.8 on 2020-08-18 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربران'},
        ),
        migrations.AlterField(
            model_name='person',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ایمیل عمومی'),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='جنسیت'),
        ),
        migrations.AlterField(
            model_name='person',
            name='likes',
            field=models.ManyToManyField(blank=True, to='main.Post', verbose_name='لایک\u200cها'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=50, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='person',
            name='programming',
            field=models.ManyToManyField(blank=True, to='main.Programming', verbose_name='زبان\u200cهای برنامه نویسی'),
        ),
        migrations.AlterField(
            model_name='person',
            name='public_email',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='person',
            name='rezome',
            field=models.TextField(blank=True, default='', null=True, verbose_name='رزومه'),
        ),
        migrations.AlterField(
            model_name='person',
            name='username',
            field=models.CharField(max_length=50, verbose_name='نام کاربری'),
        ),
        migrations.AlterField(
            model_name='person',
            name='work',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='تخصص'),
        ),
        migrations.AlterField(
            model_name='person',
            name='year_of_born',
            field=models.CharField(blank=True, choices=[('1330', '1330'), ('1331', '1331'), ('1332', '1332'), ('1333', '1333'), ('1334', '1334'), ('1335', '1335'), ('1336', '1336'), ('1337', '1337'), ('1338', '1338'), ('1339', '1339'), ('1340', '1340'), ('1341', '1341'), ('1342', '1342'), ('1343', '1343'), ('1344', '1344'), ('1345', '1345'), ('1346', '1346'), ('1347', '1347'), ('1348', '1348'), ('1349', '1349'), ('1350', '1350'), ('1351', '1351'), ('1352', '1352'), ('1353', '1353'), ('1354', '1354'), ('1355', '1355'), ('1356', '1356'), ('1357', '1357'), ('1358', '1358'), ('1359', '1359'), ('1360', '1360'), ('1361', '1361'), ('1362', '1362'), ('1363', '1363'), ('1364', '1364'), ('1365', '1365'), ('1366', '1366'), ('1367', '1367'), ('1368', '1368'), ('1369', '1369'), ('1370', '1370'), ('1371', '1371'), ('1372', '1372'), ('1373', '1373'), ('1374', '1374'), ('1375', '1375'), ('1376', '1376'), ('1377', '1377'), ('1378', '1378'), ('1379', '1379'), ('1380', '1380'), ('1381', '1381'), ('1382', '1382'), ('1383', '1383'), ('1384', '1384'), ('1385', '1385'), ('1386', '1386'), ('1387', '1387'), ('1388', '1388'), ('1389', '1389'), ('1390', '1390'), ('1391', '1391'), ('1392', '1392'), ('1393', '1393'), ('1394', '1394')], max_length=4, null=True, verbose_name='سال تولد'),
        ),
    ]
