# Generated by Django 3.1.4 on 2021-01-03 13:25

from django.db import migrations
import django.utils.timezone
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_person_date_joined'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='date_joined',
            new_name='join_time',
        ),
        migrations.AddField(
            model_name='postcomment',
            name='submit_time',
            field=django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now, verbose_name='زمان ثبت'),
        ),
    ]
