# Generated by Django 3.0.8 on 2020-08-18 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200818_0929'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'فرد', 'verbose_name_plural': 'افراد'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'مطلب', 'verbose_name_plural': 'مطالب'},
        ),
        migrations.AlterModelOptions(
            name='postcomment',
            options={'verbose_name': 'نظر مطلب', 'verbose_name_plural': 'نظرات مطالب'},
        ),
        migrations.AlterModelOptions(
            name='programming',
            options={'verbose_name': 'زبان برنامه نویسی', 'verbose_name_plural': 'زبان\u200cهای برنامه نویسی'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'پروژه', 'verbose_name_plural': 'پروژه\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='projectcomment',
            options={'verbose_name': 'نظر پروژه', 'verbose_name_plural': 'نظرات پروژه\u200cها'},
        ),
        migrations.AlterField(
            model_name='person',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=50, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='person',
            name='public_email',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ایمیل عمومی'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Person', verbose_name='نویسنده'),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(verbose_name='متن'),
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.CharField(default='0', max_length=3, verbose_name='تعداد لایک'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=50, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Person', verbose_name='نویسنده'),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Post', verbose_name='مکان'),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='replay',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='پاسخ'),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='text',
            field=models.CharField(max_length=1000, verbose_name='متن'),
        ),
        migrations.AlterField(
            model_name='programming',
            name='language',
            field=models.CharField(max_length=50, verbose_name='زبان برنامه نویسی'),
        ),
        migrations.AlterField(
            model_name='project',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Person', verbose_name='نویسنده'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='project',
            name='link_on_github',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='لینک در گیت\u200cهاب'),
        ),
        migrations.AlterField(
            model_name='project',
            name='link_on_gitlab',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='لینک در گیت\u200cلب'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=50, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='projectcomment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Person', verbose_name='نویسنده'),
        ),
        migrations.AlterField(
            model_name='projectcomment',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Project', verbose_name='مکان'),
        ),
        migrations.AlterField(
            model_name='projectcomment',
            name='replay',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='پاسخ'),
        ),
        migrations.AlterField(
            model_name='projectcomment',
            name='text',
            field=models.CharField(max_length=1000, verbose_name='متن'),
        ),
    ]
