# Generated by Django 3.1.4 on 2021-01-09 09:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210103_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000, verbose_name='متن')),
                ('submit_time', django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now, verbose_name='زمان ثبت')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.person', verbose_name='نویسنده')),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.post', verbose_name='مکان')),
                ('replays', models.ManyToManyField(blank=True, to='main.Comment', verbose_name='پاسخ\u200cها')),
            ],
            options={
                'verbose_name': 'نظر مطلب',
                'verbose_name_plural': 'نظرات مطالب',
            },
        ),
        migrations.DeleteModel(
            name='PostComment',
        ),
    ]
