# Generated by Django 3.0.8 on 2020-08-21 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_post_ads'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='متن پیام')),
                ('done', models.BooleanField(default=False, verbose_name='خوانده شده')),
                ('givver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Person', verbose_name='گیرنده')),
            ],
            options={
                'verbose_name': 'پیام',
                'verbose_name_plural': 'پیام\u200cها',
            },
        ),
    ]
