# Generated by Django 3.0.8 on 2020-08-21 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
    ]
