# Generated by Django 3.0.8 on 2020-08-21 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200821_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='notif_type',
        ),
        migrations.AddField(
            model_name='notification',
            name='noti_type',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
