# Generated by Django 3.0.8 on 2020-08-21 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20200821_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='notif_type',
        ),
    ]
