# Generated by Django 3.0.8 on 2020-08-22 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_notification_notif_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='following',
            field=models.ManyToManyField(blank=True, to='main.Person', verbose_name='دنبال شوندگان'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(default=None, max_length=10, null=True, verbose_name='نوع'),
        ),
    ]
