# Generated by Django 3.0.8 on 2020-08-23 07:21

from django.db import migrations
import django.utils.timezone
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20200822_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish_time',
            field=django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now, verbose_name='زمان انتشار'),
        ),
    ]
