# Generated by Django 3.0.8 on 2020-08-24 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_project_publish_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='images', verbose_name='آواتار'),
        ),
    ]
