# Generated by Django 3.0.8 on 2020-08-24 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20200824_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='avatar',
            field=models.ImageField(blank=True, height_field=512, upload_to='avatars/', verbose_name='آواتار', width_field=512),
        ),
    ]
