# Generated by Django 3.0.8 on 2020-08-25 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20200824_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.CharField(default='0', max_length=3, verbose_name='تعداد نظر'),
        ),
    ]
