# Generated by Django 3.0.8 on 2020-08-26 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20200826_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(blank=True, upload_to='cload/images/', verbose_name='فایل')),
            ],
        ),
        migrations.RemoveField(
            model_name='cload',
            name='files',
        ),
        migrations.DeleteModel(
            name='image',
        ),
        migrations.AddField(
            model_name='file',
            name='cload',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Cload', verbose_name='ابر'),
        ),
    ]
