# Generated by Django 3.0.8 on 2020-08-26 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20200826_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='cload',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Cload', verbose_name='ابر'),
        ),
    ]
