# Generated by Django 3.0.8 on 2020-08-26 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20200826_1134'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cload',
            new_name='Cloud',
        ),
    ]
