# Generated by Django 3.0.8 on 2020-08-26 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20200826_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cloud',
            name='available',
        ),
        migrations.AddField(
            model_name='cloud',
            name='used_percent',
            field=models.CharField(default=100, max_length=3, verbose_name='درصد استفاده شده'),
        ),
    ]
