# Generated by Django 3.0.8 on 2020-08-26 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_auto_20200826_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloud',
            name='used_percent',
            field=models.CharField(default=0, max_length=3, verbose_name='درصد استفاده شده'),
        ),
    ]
