# Generated by Django 3.0.8 on 2020-08-27 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_auto_20200826_1252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='cload',
            new_name='cloud',
        ),
    ]
