# Generated by Django 3.0.8 on 2020-08-28 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_auto_20200827_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='ads',
        ),
        migrations.AddField(
            model_name='post',
            name='cover',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='کاور'),
        ),
        migrations.AddField(
            model_name='post',
            name='short_description',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='توضیح کوتاه'),
        ),
    ]
