# Generated by Django 3.0.8 on 2020-08-30 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_project_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='short_description',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='توضیح کوتاه'),
        ),
    ]
