# Generated by Django 3.0.8 on 2020-08-31 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_project_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='comments',
            field=models.CharField(default='0', max_length=3, verbose_name='تعداد نظر'),
        ),
    ]
