# Generated by Django 3.0.8 on 2020-08-31 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_person_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='github',
            field=models.URLField(blank=True, default=None, verbose_name='گیت\u200cهاب'),
        ),
        migrations.AlterField(
            model_name='person',
            name='gitlab',
            field=models.URLField(blank=True, default=None, verbose_name='گیت\u200cلب'),
        ),
        migrations.AlterField(
            model_name='person',
            name='linkedin',
            field=models.URLField(blank=True, default=None, verbose_name='لینکدین'),
        ),
        migrations.AlterField(
            model_name='person',
            name='stackowerflow',
            field=models.URLField(blank=True, default=None, verbose_name='استک اورفلو'),
        ),
        migrations.AlterField(
            model_name='person',
            name='website',
            field=models.URLField(blank=True, default=None, verbose_name='وبسایت'),
        ),
    ]
