# Generated by Django 3.0.8 on 2020-09-03 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_auto_20200903_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='person',
            name='len_followers',
        ),
        migrations.AlterField(
            model_name='person',
            name='following',
            field=models.ManyToManyField(blank=True, to='main.Person', verbose_name='دنبال شوندگان'),
        ),
    ]
