# Generated by Django 3.0.8 on 2020-09-03 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_auto_20200903_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='len_followers',
            field=models.CharField(default=0, max_length=10, verbose_name='تعداد دنبال کنندگان'),
        ),
    ]
