# Generated by Django 3.0.8 on 2020-09-03 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_person_len_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='folllowers', to='main.Person', verbose_name='دنبال کنندگان'),
        ),
    ]
