# Generated by Django 3.0.8 on 2020-09-03 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_person_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='len_following',
            field=models.CharField(default=0, max_length=10, verbose_name='تعداد دنبال شوندگان'),
        ),
    ]
