# Generated by Django 3.0.8 on 2020-09-03 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_person_len_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='dev',
            field=models.URLField(blank=True, null=True, verbose_name='جامعه دِو'),
        ),
    ]
