# Generated by Django 3.0.8 on 2020-09-09 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_person_dev'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='viewed_posts',
            field=models.ManyToManyField(blank=True, related_name='views_post', to='main.Post', verbose_name='مطالب مشاهده شده'),
        ),
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.CharField(default='0', max_length=10, verbose_name='تعداد بازدید'),
        ),
        migrations.AlterField(
            model_name='post',
            name='comments',
            field=models.CharField(default='0', max_length=10, verbose_name='تعداد نظر'),
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.CharField(default='0', max_length=10, verbose_name='تعداد لایک'),
        ),
    ]
