# Generated by Django 3.0.8 on 2020-09-15 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_auto_20200909_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(max_length=50, null=True, verbose_name='دسته بندی'),
        ),
    ]
