# Generated by Django 3.0.8 on 2020-09-16 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='project_description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات پروژه'),
        ),
        migrations.AddField(
            model_name='post',
            name='project_github',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='لینک در گیت\u200cهاب'),
        ),
        migrations.AddField(
            model_name='post',
            name='project_gitlab',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='لینک در گیت\u200cلب'),
        ),
        migrations.AddField(
            model_name='post',
            name='project_lang',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='زبان پروژه'),
        ),
        migrations.AddField(
            model_name='post',
            name='project_license',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='لایسنس پروژه'),
        ),
        migrations.AddField(
            model_name='post',
            name='project_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نام پروژه'),
        ),
    ]
