# Generated by Django 3.0.8 on 2020-09-16 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_auto_20200916_0616'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='project',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
