# Generated by Django 3.0.8 on 2020-09-18 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_post_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloud',
            name='space',
            field=models.CharField(default=100, max_length=100, verbose_name='فضا'),
        ),
        migrations.AlterField(
            model_name='cloud',
            name='used_space',
            field=models.CharField(default=0, max_length=100, verbose_name='فضای استفاده شده'),
        ),
    ]
