# Generated by Django 3.0.8 on 2020-09-26 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_auto_20200918_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default_avatar/', upload_to='avatars/', verbose_name='آواتار'),
        ),
    ]
