# Generated by Django 3.0.8 on 2020-10-21 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0058_auto_20201021_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='available_views',
            field=models.CharField(default=100, max_length=10, verbose_name='بازدید باقی مانده'),
        ),
    ]
