# Generated by Django 3.0.8 on 2020-11-21 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0060_auto_20201027_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='short_description',
            field=models.TextField(blank=True, max_length=156, null=True, verbose_name='توضیح کوتاه'),
        ),
    ]
