# Generated by Django 3.0.8 on 2020-12-14 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0061_auto_20201121_0910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='project',
        ),
        migrations.RemoveField(
            model_name='post',
            name='project_description',
        ),
        migrations.RemoveField(
            model_name='post',
            name='project_github',
        ),
        migrations.RemoveField(
            model_name='post',
            name='project_gitlab',
        ),
        migrations.RemoveField(
            model_name='post',
            name='project_lang',
        ),
        migrations.RemoveField(
            model_name='post',
            name='project_license',
        ),
        migrations.RemoveField(
            model_name='post',
            name='project_name',
        ),
    ]
